# NumPy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing and Slicing

In [ ]:
arr[8] # <- value of index 8

8

In [5]:
arr[1:5] # start index and end index like Python slicing

array([1, 2, 3, 4])

In [7]:
arr[0:5] #inclusive

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[8:]

array([ 8,  9, 10])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

In [11]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Imp Slicing Note

In [12]:
arr = np.arange(0,11)

In [14]:
slice_of_array = arr[0:6]
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr # changes it on the original array too and data is not copied and is just a view

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Copying

In [17]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2d Arrays

In [21]:
arr_2d = np.array([[5,10,15], [20,25,30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Double Bracket Format

In [22]:
arr_2d[0][0]

5

In [23]:
arr_2d[0]

array([ 5, 10, 15])

### Comma Single Bracket Notation (Recommended)

In [24]:
arr_2d[0,0]

5

### Using Slice Notation

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[:2, 1:] #slice up until 2nd row and first col until the end

array([[10, 15],
       [25, 30]])

In [27]:
arr_2d[1:,1: ]

array([[25, 30],
       [40, 45]])

In [28]:
arr_2d[:2, :2]

array([[ 5, 10],
       [20, 25]])

## Conditional Selection

Returns boolean values

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [33]:
bool_arr = arr > 5 
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[bool_arr] # will only select the indices where bool array is true

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr > 5] # all in one step

array([ 6,  7,  8,  9, 10])

In [36]:
arr[arr < 3]

array([0, 1, 2])