In [1]:
#creatng a numpy array 
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np 
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [ ]:
#creating a matrix - casting a list of lists 
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_mat)
#numbers of brackets show how many dimensions there are
#this is a very manual way to do it tho 


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Common Way to Make Arrays in Numpy

In [ ]:
np.arange(0, 10) #indexing starts at 0 but not including 10 same as range()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 11, 2) #step size argument like the range()

array([ 0,  2,  4,  6,  8, 10])

### Specific Types of Arrays

In [8]:
np.zeros(10) # one dimensional vector of 0's

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,3)) # can also make dimensions 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(4) 

array([1., 1., 1., 1.])